### ISSUE TITLE
Mikser not starting up

### ISSUE THREAD

**Issue by scotrod** [almero-digital-marketing/mikser#20]
Environment:
Win10 Pro 20h2
NodE.JS VER - v12.18.3 
MongoDB VER - 4.4

Issue: upon starting, I get the following error:

```
D:\mikser\mikser\mikser>mikser
Mikser: 7.9.13
Working folder: D:\mikser\mikser\mikser
Plugins: markdown,textile,swig,ect,twig,pug,ejs,yaml,toml,json,cson,csv,archieml,nunjucks,browser,livereload,feedback,switch,gate
Mongo: C:\Program Files\MongoDB\Server\4.4\bin\mongod.exe

D:\mikser\mikser\mikser>
```

And nothing else, the server doesn't start.
Any ideas on how can I resolve this?

**Comment by dimitarkolev** [comment]
Can you run it with `mikser -d` to get the full debug log.

**Comment by scotrod** [comment]
```
D:\mikser\mikser\mikser>mikser -d
Mikser: 7.11.1
Working folder: D:\mikser\mikser\mikser
config 0 D:\mikser\mikser\mikser\mikser.yml
Plugins: markdown,textile,swig,ect,twig,pug,ejs,yaml,toml,json,cson,csv,archieml,nunjucks,browser,livereload,feedback,switch,gate
Mongo: C:\Program Files\MongoDB\Server\4.4\bin\mongod.exe
Unhandled rejection TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (10816)
    at Object.writeFileSync (fs.js:1460:5)
    at C:\Users\user\AppData\Roaming\npm\node_modules\mikser\lib\database.js:141:10
    at Promise.cancellationExecute [as _execute] (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:103:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\mikser\lib\database.js:118:13
    at tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

```
I reinstalled nodejs, mongodb and mikser twice to make sure that it was not installation failure or issue.

**Comment by scotrod** [comment]
Any resolution on this?
I tried this setup on a separate machine (fresh Windows reinstall) same problem.

**Comment by dimitarkolev** [comment]
Just pushed a fix: mikser@7.11.2

**Comment by scotrod** [comment]
Sorry for bothering again, but I'm still getting similar issue.

`C:\Users\User\New folder>mikser                                                                                                                                         Mikser: 7.11.2                                                                                                                                                          Working folder: C:\Users\User\New folder                                                                                                                                Plugins: markdown,textile,swig,ect,twig,pug,ejs,yaml,toml,json,cson,csv,archieml,nunjucks,browser,livereload,feedback,switch,gate                                       Mongo: C:\Program Files\MongoDB\Server\4.4\bin\mongod.exe                                                                                                               Unhandled rejection TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (8772)                                                                                                                                                                     at Object.writeFileSync (fs.js:1460:5)                                                                                                                                  at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:141:10                                                                                         at Promise.cancellationExecute [as _execute] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\debuggability.js:406:9)            at Promise._resolveFromExecutor (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:518:18)                              at new Promise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:103:10)                                               at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:118:13                                                                                         at tryCatcher (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\util.js:16:23)    at Promise._settlePromiseFromHandler (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:547:31)                                                                         at Promise._settlePromise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:604:18)                                    at Promise._settlePromiseCtx (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:641:10)                                 at _drainQueueStep (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:97:12)                                              at _drainQueue (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:86:9)                                                   at Async._drainQueues (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:102:5)                                           at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:15:14)                at processImmediate (internal/timers.js:461:21)    `

This again is on separate Windows machine, no previous mikser installs.

**Comment by dimitarkolev** [comment]
Can you try it now ( mikser@7.11.3)?

**Comment by scotrod** [comment]
Worked like a charm.
Thanks!
