### ISSUE TITLE
First run - cannot startup Mikser

### ISSUE THREAD

**Issue by scotrod** [almero-digital-marketing/mikser#44]
Hello,

I installed Mikser via `npm install -g mikser` and I created a test folder for my project.

Upon first start, I get just the following error:

```

PS C:\Users\User\Desktop\WORK\miksertest> mikser
Mikser: 7.12.10
Working folder: C:\Users\User\Desktop\WORK\miksertest
Plugins: markdown,textile,swig,ect,twig,pug,ejs,yaml,toml,json,cson,csv,archieml,nunjucks,browser,livereload,feedback,switch,gate
Mongo: C:\Program Files\MongoDB\Server\6.0\bin\mongod.exe
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'pid')
    at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:141:64
    at Promise.cancellationExecute [as _execute] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:103:10)
    at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:118:13
    at tryCatcher (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\util.js:16:23)    at Promise._settlePromiseFromHandler (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
PS C:\Users\User\Desktop\WORK\miksertest>

```

Environment:
OS: Windows 11 Pro x64 (VM)
Node.js ver: v18.14.0
MongoDB ver: v6.0.4

Running Mikser with full debul log:

```

PS C:\Users\User\Desktop\WORK\miksertest> mikser -d
Mikser: 7.12.10
Working folder: C:\Users\User\Desktop\WORK\miksertest
config 0 C:\Users\User\Desktop\WORK\miksertest\mikser.yml
Plugins: markdown,textile,swig,ect,twig,pug,ejs,yaml,toml,json,cson,csv,archieml,nunjucks,browser,livereload,feedback,switch,gate
Mongo: C:\Program Files\MongoDB\Server\6.0\bin\mongod.exe
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'pid')
    at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:141:64
    at Promise.cancellationExecute [as _execute] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:103:10)
    at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:118:13
    at tryCatcher (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)

PS C:\Users\User\Desktop\WORK\miksertest>

```

Mikser is being run under Windows Terminal (Powershell) as an admin.

Thanks!

**Comment by dimitarkolev** [comment]
I believe you are using nidejs 18 or newer. Unfortunately this version of mikser is compatible only with nidejs 16 and earlier. If you have nvm installed it's easy to switch. You need to have mongodb installed as well.

We are working heavily on a mikser successor called mikser-core which is 10x faster works with latest nodejs versions and does not require mongodb. It has vite integration for live reload, Supports documents from Payloadjs, Directus or any other CMS platform with very simple configuration. This new version is feature complete and published to npm but we are just about to start working on the documentation. It's not fully compatible with the previous one but from our experience we can convert huge project with thousand of document and hundred layouts in about a week. For smaller scale mikser project it will take few hours.

**Comment by scotrod** [comment]
Thank you for the explanation!

My project is really slow, but I have to start working on it. Using nodejs 16x didn't solved it for me. I will try to wipe down everything and start from scratch. Will let you know if it works.

```

PS C:\Users\User\Desktop\WORK\mikser_test> nvm list

    18.14.0
  * 16.18.1 (Currently using 64-bit executable)
PS C:\Users\User\Desktop\WORK\mikser_test> mikser
Mikser: 7.12.10
Working folder: C:\Users\User\Desktop\WORK\mikser_test
Plugins: markdown,textile,swig,ect,twig,pug,ejs,yaml,toml,json,cson,csv,archieml,nunjucks,browser,livereload,feedback,switch,gate
Mongo: C:\Program Files\MongoDB\Server\6.0\bin\mongod.exe
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'pid')
    at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:141:64
    at Promise.cancellationExecute [as _execute] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:103:10)
    at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:118:13
    at tryCatcher (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\util.js:16:23)    at Promise._settlePromiseFromHandler (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:466:21)

PS C:\Users\User\Desktop\WORK\mikser_test>

```

**Comment by scotrod** [comment]
Setup with fresh install of nodejs 16 isn't working as well. Should I downgrade to 15?

```

C:\Users\User\Desktop\mikser\test1>mikser                                                                               Mikser: 7.12.10                                                                                                         Working folder: C:\Users\User\Desktop\mikser\test1                                                                      Plugins: markdown,textile,swig,ect,twig,pug,ejs,yaml,toml,json,cson,csv,archieml,nunjucks,browser,livereload,feedback,switch,gate                                                                                                               Mongo: C:\Program Files\MongoDB\Server\6.0\bin\mongod.exe                                                               Unhandled rejection TypeError: Cannot read properties of undefined (reading 'pid')                                          at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:141:64                                         at Promise.cancellationExecute [as _execute] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\debuggability.js:406:9)                                                                                    at Promise._resolveFromExecutor (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:518:18)                                                                                                      at new Promise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:103:10)                                                                                                                       at C:\Users\User\AppData\Roaming\npm\node_modules\mikser\lib\database.js:118:13                                         at tryCatcher (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\util.js:16:23)    at Promise._settlePromiseFromHandler (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:547:31)                                                                                                 at Promise._settlePromise (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:604:18)                                                                                                            at Promise._settlePromiseCtx (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\promise.js:641:10)                                                                                                         at _drainQueueStep (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:97:12)                                                                                                                      at _drainQueue (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:86:9)                                                                                                                           at Async._drainQueues (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:102:5)                                                                                                                   at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\User\AppData\Roaming\npm\node_modules\mikser\node_modules\bluebird\js\release\async.js:15:14)                                                                                        at processImmediate (node:internal/timers:466:21)                                                                                                                                                                                                                                                                                                                   C:\Users\User\Desktop\mikser\test1>node -v                                                                              v16.16.0                                                                                                                                                                                                                                        C:\Users\User\Desktop\mikser\test1>

```
